import LegalPage from "../components/legal/LegalPage";
import { email } from "../config/contact";

// Privacy Policy for the public website tridentrisk.org. Describes only the
// processing the site actually carries out (audited): enquiry/request forms via
// web3forms, mailto enquiries, downloadable reports, hosting/server data, Google
// Fonts, and — only with consent — Google Analytics. No newsletter processor is
// operated. Retention is stated conservatively; rights are framed by applicable
// law. Full registered-entity details are flagged for the owner, not invented.

const UPDATED = "15 August 2026";

const sections = [
  {
    id: "who-we-are",
    heading: "Who we are",
    blocks: [
      "This website is operated by Trident FZC LLC, trading as Trident Risk & Advisory (\"Trident\", \"we\", \"us\"), a maritime, geopolitical and legal risk advisory business. This Privacy Policy explains how we handle personal information in connection with our public website at tridentrisk.org (the \"website\").",
      "It covers the website only. It does not govern any separate client engagement, which is dealt with under its own agreement.",
      `If you have any questions about this policy or how your information is handled, contact us at ${email}.`,
    ],
  },
  {
    id: "information-we-collect",
    heading: "Information we collect",
    blocks: [
      "We collect only the information needed to respond to you and to run the website. This includes:",
      {
        list: [
          "Information you provide when you make an enquiry or request support — typically your name, organisation, email address, the service or subject your enquiry relates to, and the content of your message.",
          "Information you provide when you request a report that is made available for download — your email address, and your organisation if you choose to provide it.",
          "Anything else you choose to include when you email us directly (for example, a telephone number in your message).",
          "Technical information generated automatically when you visit the website, such as your IP address, browser type and the pages you view, processed as part of hosting and delivering the site.",
          "With your consent, anonymous analytics information about how the website is used — such as pages viewed, content and services of interest, and how visitors move through the site (see Cookies and similar technologies). We do not send your email address, name or organisation to our analytics provider, and we do not use analytics to identify you individually.",
        ],
      },
      "We do not ask for special categories of personal data through the website, and you should not send us sensitive information through it.",
    ],
  },
  {
    id: "how-we-collect",
    heading: "How we collect it",
    blocks: [
      {
        list: [
          "Directly from you — when you complete a request form, request a report, or email us.",
          "Automatically — through standard server logs generated by our hosting provider, and, only where you have consented, through analytics.",
        ],
      },
    ],
  },
  {
    id: "why-we-use-it",
    heading: "Why we use your information",
    blocks: [
      { list: [
        "To respond to your enquiry and provide the information or support you have asked for.",
        "To provide reports you have requested.",
        "To operate, maintain and secure the website.",
        "To understand how the website is used and improve it — only where you have consented to analytics.",
        "To meet our legal, regulatory and record-keeping obligations.",
      ] },
      "We do not sell your personal information, and we do not use the website to send marketing.",
    ],
  },
  {
    id: "legal-grounds",
    heading: "Legal grounds",
    blocks: [
      "Where data protection law applies to our processing, we rely on one or more of the following grounds, depending on the situation:",
      { list: [
        "Your consent — for analytics, and for handling a report request you submit.",
        "Our legitimate interests — in responding to enquiries, running and securing the website, and understanding its use, balanced against your interests and rights.",
        "Compliance with a legal obligation — where we are required to retain or disclose information by law.",
      ] },
    ],
  },
  {
    id: "enquiries",
    heading: "Enquiries and requests",
    blocks: [
      "Some parts of the website let you contact us by email using your own email application. In that case, your message is sent directly to us and contains whatever information you choose to include.",
      "Our request form is submitted through a third-party form-handling service (Web3Forms), which delivers the submission to us by email. The information you enter in that form is processed by that service for the purpose of delivering it to us.",
    ],
  },
  {
    id: "reports",
    heading: "Website reports",
    blocks: [
      "To download a full report, we ask for your email address (and, optionally, your organisation). We use these details to provide the report and to understand interest in Trident's analysis. Requesting a report does not subscribe you to marketing.",
      "The report-access form is handled in the same way as our request form (through Web3Forms), which delivers your submission to us by email. Your email address is not passed to our analytics provider.",
    ],
  },
  {
    id: "newsletter",
    heading: "Newsletter",
    blocks: [
      "We do not currently operate an automated newsletter or subscriber list through this website. If you would like to receive occasional operational briefings and analysis, contact us directly and we will arrange this with you.",
    ],
  },
  {
    id: "technical-data",
    heading: "Technical and hosting data",
    blocks: [
      "The website is delivered by our hosting provider (Vercel). As part of serving the website, standard technical data such as IP address and browser information may be processed to deliver content, maintain security and keep the service running.",
      "The website also loads fonts from Google Fonts and, on some pages, images hosted by third-party providers. When these load, the provider receives your IP address in order to deliver the resource. These requests do not set advertising or tracking cookies.",
    ],
  },
  {
    id: "cookies",
    heading: "Cookies and similar technologies",
    blocks: [
      "The website uses only strictly necessary storage by default, together with Google Analytics where you have given consent. It does not use advertising or marketing cookies.",
      "Full details, and the controls to change your choice, are set out in our Cookie Policy.",
    ],
  },
  {
    id: "service-providers",
    heading: "Service providers",
    blocks: [
      "We use a small number of third parties to run the website. Each processes personal information only as needed to provide its service:",
      { list: [
        "Web3Forms — handles submissions from our request and report forms and delivers them to us.",
        "Google — provides Google Fonts (font delivery) and, only with your consent, Google Analytics (website usage measurement).",
        "Vercel — hosts and delivers the website.",
      ] },
    ],
  },
  {
    id: "international",
    heading: "International processing",
    blocks: [
      "Trident is based in the United Arab Emirates and operates internationally, and the service providers above may process information in other countries. This means your personal information may be processed outside the country in which you are located.",
      "Where personal information is transferred internationally, we take reasonable steps for it to remain protected in line with applicable law.",
    ],
  },
  {
    id: "retention",
    heading: "Data retention",
    blocks: [
      "We retain personal information only for as long as reasonably necessary for the purpose for which it was collected, including to meet applicable legal, regulatory and record-keeping requirements. When it is no longer needed, we take reasonable steps to delete or anonymise it.",
    ],
  },
  {
    id: "security",
    heading: "Security",
    blocks: [
      "We take reasonable technical and organisational measures to protect personal information handled through the website. No method of transmission over the internet or electronic storage is completely secure, and we cannot guarantee absolute security.",
    ],
  },
  {
    id: "your-rights",
    heading: "Your rights",
    blocks: [
      "Depending on where you are located and the law that applies, you may have some or all of the following rights in relation to your personal information:",
      { list: [
        "To access the information we hold about you.",
        "To have inaccurate information corrected.",
        "To have information deleted in certain circumstances.",
        "To object to, or ask us to restrict, certain processing.",
        "To receive certain information in a portable form.",
        "To withdraw consent where we rely on it, including for analytics.",
      ] },
      `To exercise any of these rights, contact us at ${email}. Depending on your location, you may also have the right to complain to a data protection or supervisory authority.`,
    ],
  },
  {
    id: "other-sites",
    heading: "Links to other websites",
    blocks: [
      "The website may link to third-party websites. We are not responsible for the content or privacy practices of those websites, and this policy does not apply to them.",
    ],
  },
  {
    id: "changes",
    heading: "Changes to this policy",
    blocks: [
      "We may update this policy from time to time. The date at the top of this page shows when it was last updated. Please check back periodically.",
    ],
  },
  {
    id: "contact",
    heading: "Contact",
    blocks: [
      `For any question about this policy or your personal information, contact us at ${email}.`,
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      updated={UPDATED}
      intro="How Trident Risk & Advisory handles personal information in connection with this website."
      sections={sections}
    />
  );
}
